//@version=5
strategy("Stoch strat", overlay=true)


fastLength = input(12)
slowlength = input(26)
MACDLength = input(9)
MACD = ta.ema(close, fastLength) - ta.ema(close, slowlength)
aMACD = ta.ema(MACD, MACDLength)
delta = MACD - aMACD


length = input.int(14, minval=1)
OverBought = input(80)
OverSold = input(20)
smoothK = 3
smoothD = 3

checkhigh = ta.ema(close,100)
checklow = ta.ema(close,50)

k = ta.sma(ta.stoch(close, high, low, length), smoothK)
d = ta.sma(k, smoothD)
co = ta.crossover(k,d)
cu = ta.crossunder(k,d)

if (not na(k) and not na(d))
	if (co and k < OverSold and close > checkhigh and checklow > checkhigh and ta.crossover(delta, 0))
		strategy.entry("Long entry", strategy.long, comment="StochLE")
		
	if (cu and k > OverBought and close < checkhigh and checklow < checkhigh and ta.crossunder(delta, 0))
		strategy.entry("Short entry", strategy.short, comment="StochSE")
		
		
		
strategy.exit("long exit","Long entry", profit = close * .02 / syminfo.mintick, loss = close * .01 / syminfo.mintick)
strategy.exit("short exit","Short entry", profit = close * .02 / syminfo.mintick, loss = close * .01 / syminfo.mintick)